package calc;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.BufferedReader;
import java.util.Scanner;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
public class teacherwelcomepage extends javax.swing.JFrame {
    String user=null;
    int key;
   
    public teacherwelcomepage(String user) {
        this.user=user;
        initComponents();
        welcomenote.setText("HELLO  "+this.user);
    }
    public teacherwelcomepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        createtest = new javax.swing.JButton();
        welcomenote = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        info = new javax.swing.JMenuItem();
        changepsswd = new javax.swing.JMenuItem();
        prequiz = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createtest.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        createtest.setText("CREATE TEST");
        createtest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createtestActionPerformed(evt);
            }
        });

        welcomenote.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N

        jMenu2.setForeground(java.awt.Color.black);
        jMenu2.setText("PROFILE");

        info.setText("ABOUT YOU");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        jMenu2.add(info);

        changepsswd.setText("EDIT DETAILS");
        changepsswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepsswdActionPerformed(evt);
            }
        });
        jMenu2.add(changepsswd);

        prequiz.setText("EDIT PREVIOUS QUIZZES");
        prequiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prequizActionPerformed(evt);
            }
        });
        jMenu2.add(prequiz);

        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu2.add(logout);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(java.awt.Color.black);
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createtest, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addComponent(welcomenote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(welcomenote, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(createtest)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        // TODO add your handling code here:
      try {
            Socket socket = new Socket("localhost", 5411);
            sendMessage(socket);
        } catch (IOException e)
        {   e.printStackTrace();
        }
    }//GEN-LAST:event_infoActionPerformed

    private void changepsswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepsswdActionPerformed
        // TODO add your handling code here:
        dispose();
        new Changepswd(user).setVisible(true);
    }//GEN-LAST:event_changepsswdActionPerformed

    private void prequizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prequizActionPerformed
       key=2;
       dispose();
        new Createtest(key,this.user).setVisible(true);
        
    }//GEN-LAST:event_prequizActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        dispose();
        new logink().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void createtestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createtestActionPerformed
        // TODO add your handling code here:
        dispose();
        new Createtest(user).setVisible(true);
    }//GEN-LAST:event_createtestActionPerformed

    public void sendMessage 
            (Socket socket)
            throws IOException{
               
        ObjectOutputStream objectOutputStream =
                new ObjectOutputStream(socket.getOutputStream());
            objectOutputStream.writeUTF(user);
            objectOutputStream.flush();
            ObjectInputStream objectinputstream=new ObjectInputStream(socket.getInputStream());
            String s1,s2,s3,s4,s5;
            s5=(String) objectinputstream.readUTF();
            dispose();
            new teacherinfo(user,s5).setVisible(true);
                             }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherwelcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherwelcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherwelcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherwelcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherwelcomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem changepsswd;
    private javax.swing.JButton createtest;
    private javax.swing.JMenuItem info;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem prequiz;
    private javax.swing.JLabel welcomenote;
    // End of variables declaration//GEN-END:variables
}
